services:
  - type: web
    name: rootfinder-pro
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_ORIGIN
        value: https://rootfindermn.onrender.com
      - key: CORS_ORIGINS
        value: https://rootfindermn.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
